import { z } from 'zod/mini';

export const vesselSchema = z.object({
    uuid: z.string(),
    name: z.nullable(z.string()),
    mmsi: z.nullable(z.string()),
    imo: z.nullable(z.string()),
    eni: z.nullable(z.string()),
    country_iso: z.nullable(z.string()),
    type: z.nullable(z.string()),
    type_specific: z.nullable(z.string()),
    lat: z.nullable(z.number()),
    lon: z.nullable(z.number()),
    speed: z.nullable(z.number()),
    course: z.nullable(z.number()),
    navigational_status: z.nullable(z.string()),
    heading: z.nullable(z.number()),
    destination: z.nullable(z.string()),
    last_position_epoch: z.nullable(z.number()),
    last_position_UTC: z.nullable(z.string()),
});

export const vesselProSchema = z.object({
    uuid: z.string(),
    name: z.nullable(z.string()),
    mmsi: z.nullable(z.string()),
    imo: z.nullable(z.string()),
    eni: z.nullable(z.string()),
    country_iso: z.nullable(z.string()),
    type: z.nullable(z.string()),
    type_specific: z.nullable(z.string()),
    lat: z.nullable(z.number()),
    lon: z.nullable(z.number()),
    current_draught: z.nullable(z.number()),
    speed: z.nullable(z.number()),
    course: z.nullable(z.number()),
    navigational_status: z.nullable(z.string()),
    heading: z.nullable(z.number()),
    destination: z.nullable(z.string()),
    dest_port: z.nullable(z.string()),
    dest_port_unlocode: z.nullable(z.string()),
    dep_port: z.nullable(z.string()),
    dep_port_unlocode: z.nullable(z.string()),
    last_position_epoch: z.nullable(z.number()),
    last_position_UTC: z.nullable(z.string()),
    atd_epoch: z.nullable(z.number()),
    atd_UTC: z.nullable(z.string()),
    eta_epoch: z.nullable(z.number()),
    eta_UTC: z.nullable(z.string()),
});

export const vesselBulkSchema = z.object({
    total: z.number(),
    vessels: z.array(
        z.object({
            uuid: z.string(),
            name: z.nullable(z.string()),
            mmsi: z.nullable(z.string()),
            imo: z.nullable(z.string()),
            eni: z.nullable(z.string()),
            country_iso: z.nullable(z.string()),
            type: z.nullable(z.string()),
            type_specific: z.nullable(z.string()),
            lat: z.nullable(z.number()),
            lon: z.nullable(z.number()),
            speed: z.nullable(z.number()),
            course: z.nullable(z.number()),
            heading: z.nullable(z.number()),
            navigation_status: z.nullable(z.string()),
            destination: z.nullable(z.string()),
            last_position_epoch: z.nullable(z.number()),
            last_position_UTC: z.nullable(z.string()),
            eta_epoch: z.nullable(z.number()),
            eta_UTC: z.nullable(z.string()),
        }),
    ),
});
